# Optimized for Coolify deployment
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    # Minimal resource configuration
    mem_limit: 256m
    memswap_limit: 256m
    cpu_shares: 512

    # Environment variables
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=200

    # Security
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    # Volumes for persistent logs
    volumes:
      - logs:/app/logs

    # Health check for Coolify monitoring
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 60s
      timeout: 10s
      retries: 3

volumes:
  logs:
    driver: local